"""
AI-powered Root Cause Analysis using Google Gemini.

Analyzes health check data collected from the OCP cluster and produces
a structured RCA with correlated failures, root causes, and remediation steps.

Implementation is split across ``ai_prompts``, ``ai_gemini``, ``ai_investigate``,
and ``ai_md_to_html``. This module re-exports the public API.
"""
from healthchecks.ai_gemini import (
    GEMINI_MODEL,
    INVESTIGATE_MODEL,
    analyze_with_gemini,
    suggest_new_patterns,
    suggest_root_cause_rules,
)
from healthchecks.ai_investigate import (
    BLOCKED_PATTERNS,
    SAFE_CMD_PREFIXES,
    ai_investigate,
    is_safe_command,
)
from healthchecks.ai_md_to_html import _md_to_html
from healthchecks.ai_prompts import (
    AI_ANALYZE_SYSTEM,
    AI_INVESTIGATE_SYSTEM,
    PATTERN_SUGGESTION_PROMPT,
    RC_RULE_SUGGESTION_PROMPT,
    SYSTEM_PROMPT,
)


def generate_ai_rca_html(ai_markdown):
    """Convert AI-generated markdown RCA into an HTML section for the report."""
    if not ai_markdown:
        return ""

    try:
        html_content = _md_to_html(ai_markdown)
    except Exception:
        from html import escape
        html_content = f"<pre>{escape(ai_markdown)}</pre>"

    return f"""
    <div class="dash-section" style="margin-top:24px;border:1px solid #5794F2;border-radius:8px;">
        <div class="dash-section-title" style="background:linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);border-bottom:2px solid #5794F2;">
            <span style="font-size:1.3em;">🤖 AI Root Cause Analysis</span>
            <span style="font-size:0.75em;color:#888;margin-left:12px;">Powered by Gemini</span>
        </div>
        <div style="padding:20px;background:#111217;font-size:0.95em;line-height:1.6;">
            <div style="background:#1a1a2e;border-left:3px solid #FF9830;padding:10px 14px;margin-bottom:16px;border-radius:4px;font-size:0.85em;color:#888;">
                This analysis was generated by AI and should be verified by an engineer.
            </div>
            {html_content}
        </div>
    </div>
    """
