"""Drill-down and follow-up command tables for RCA."""

DRILLDOWN_COMMANDS = {
    "node-not-ready": [
        {"cmd": "oc describe node {name} 2>&1 | grep -A30 'Conditions:'", "desc": "Full node conditions (DiskPressure, MemoryPressure, PIDPressure, Ready)"},
        {"cmd": "oc get events --field-selector involvedObject.name={name},reason!=NodeHasSufficientMemory,reason!=NodeHasNoDiskPressure --sort-by='.lastTimestamp' 2>&1 | tail -20", "desc": "Significant node events (excluding routine)"},
        {"cmd": "oc describe node {name} 2>&1 | grep -A5 'Ready\\|MemoryPressure\\|DiskPressure\\|PIDPressure'", "desc": "Node condition reasons and messages"},
        {"cmd": "oc get pods --field-selector spec.nodeName={name} -A --no-headers 2>&1 | grep -ciE 'evict|unknown|pending'", "desc": "Count of Evicted/Unknown/Pending pods on this node"},
        {"cmd": "oc get node {name} -o wide 2>&1 | tail -1 | awk '{print $6}'", "desc": "Node internal IP (for SSH check)"},
        {"cmd": "oc adm top node {name} 2>&1", "desc": "Node resource usage (fails if node is dead)"},
    ],
    "node-disk-pressure": [
        {"cmd": "ssh -o ConnectTimeout=8 -o StrictHostKeyChecking=no core@{node_ip} 'df -h /var /var/lib/kubelet /sysroot 2>/dev/null; echo --- ; df -ih /var 2>/dev/null'", "desc": "Filesystem usage on the node (blocks + inodes)"},
        {"cmd": "ssh -o ConnectTimeout=8 -o StrictHostKeyChecking=no core@{node_ip} 'sudo du -sh /var/lib/containers /var/lib/kubelet /var/log /var/lib/etcd 2>/dev/null | sort -rh'", "desc": "Top /var consumers breakdown (containers, kubelet, logs, etcd)"},
        {"cmd": "ssh -o ConnectTimeout=8 -o StrictHostKeyChecking=no core@{node_ip} 'sudo sh -c \"du -sh /var/lib/kubelet/pods/* 2>/dev/null | sort -rh | head -10\"'", "desc": "Top 10 pods by ephemeral disk usage under kubelet/pods"},
        {"cmd": "ssh -o ConnectTimeout=8 -o StrictHostKeyChecking=no core@{node_ip} 'sudo sh -c \"du -sh /var/lib/containers/storage/overlay/* 2>/dev/null | sort -rh | head -10\"'", "desc": "Top 10 container image layers by disk usage"},
        {"cmd": "ssh -o ConnectTimeout=8 -o StrictHostKeyChecking=no core@{node_ip} 'sudo sh -c \"du -sh /var/log/pods/* 2>/dev/null | sort -rh | head -10\"'", "desc": "Top 10 pods by log disk usage"},
        {"cmd": "ssh -o ConnectTimeout=8 -o StrictHostKeyChecking=no core@{node_ip} 'sudo sh -c \"for d in $(ls /var/lib/kubelet/pods/ 2>/dev/null | head -5); do sz=$(du -sh /var/lib/kubelet/pods/$d 2>/dev/null | cut -f1); vols=$(ls /var/lib/kubelet/pods/$d/volumes/kubernetes.io~empty-dir/ 2>/dev/null | tr \\\\n ,); echo $sz $d emptyDirs=$vols; done\" | sort -rh'", "desc": "Top 5 pod UUIDs with size and emptyDir volume names (identifies workload)"},
        {"cmd": "oc describe node {name} 2>&1 | grep -B2 -A5 'DiskPressure'", "desc": "DiskPressure condition details"},
        {"cmd": "oc get pods --field-selector spec.nodeName={name} -A --no-headers 2>&1 | grep -i evict | head -10", "desc": "Evicted pods on this node"},
        {"cmd": "oc get events -A --sort-by='.lastTimestamp' 2>&1 | grep -i 'evict\\|disk\\|pressure\\|space' | tail -15", "desc": "Cluster events related to disk/eviction"},
    ],
    "node-memory-pressure": [
        {"cmd": "oc describe node {name} 2>&1 | grep -B2 -A5 'MemoryPressure'", "desc": "MemoryPressure condition details"},
        {"cmd": "oc describe node {name} 2>&1 | grep -A5 'Ready\\|MemoryPressure\\|DiskPressure\\|PIDPressure'", "desc": "All node conditions with reasons"},
        {"cmd": "oc adm top pods --field-selector spec.nodeName={name} -A --no-headers 2>&1 | sort -k3 -rh | head -15", "desc": "Top memory consuming pods on this node"},
        {"cmd": "oc adm top node {name} 2>&1", "desc": "Node overall resource usage"},
        {"cmd": "oc get pods --field-selector spec.nodeName={name} -A --no-headers 2>&1 | wc -l", "desc": "Total pod count on this node"},
        {"cmd": "oc get events -A --field-selector reason=OOMKilled --sort-by='.lastTimestamp' 2>&1 | tail -10", "desc": "Recent OOM kill events cluster-wide"},
        {"cmd": "oc get pods --field-selector spec.nodeName={name} -A --no-headers 2>&1 | grep -ciE 'evict|oom'", "desc": "Count of evicted/OOM pods on this node"},
    ],
    "node-cordoned": [
        {"cmd": "oc describe node {name} 2>&1 | grep -A10 'Taints:'", "desc": "Node taints (shows cordon reason)"},
        {"cmd": "oc get mcp 2>&1", "desc": "MachineConfigPool status (node may be updating)"},
        {"cmd": "oc get events --field-selector involvedObject.name={name} --sort-by='.lastTimestamp' 2>&1 | grep -iE 'drain|cordon|taint|schedule' | tail -10", "desc": "Drain/cordon events"},
        {"cmd": "oc get nodes {name} -o yaml 2>&1 | grep -A5 'unschedulable'", "desc": "Unschedulable flag details"},
    ],
    "operator-crashloop": [
        {"cmd": "oc get pods -n openshift-{name} --no-headers 2>&1 | grep -v Running | head -10", "desc": "Non-running pods in operator namespace"},
        {"cmd": "oc logs -n openshift-{name} $(oc get pods -n openshift-{name} --no-headers 2>/dev/null | grep -v Running | head -1 | awk '{print $1}') --previous --tail=50 2>&1 | tail -30", "desc": "Previous container logs (crash reason)"},
        {"cmd": "oc describe pod -n openshift-{name} $(oc get pods -n openshift-{name} --no-headers 2>/dev/null | grep -v Running | head -1 | awk '{print $1}') 2>&1 | grep -A10 'Last State:'", "desc": "Last container state (exit code, reason)"},
        {"cmd": "oc describe pod -n openshift-{name} $(oc get pods -n openshift-{name} --no-headers 2>/dev/null | grep -v Running | head -1 | awk '{print $1}') 2>&1 | grep -A5 'Resources:'", "desc": "Pod resource limits"},
        {"cmd": "oc get events -n openshift-{name} --sort-by='.lastTimestamp' 2>&1 | tail -15", "desc": "Recent events in operator namespace"},
    ],
    "pod-app-crash": [
        {"cmd": "oc logs {pod} -n {ns} --previous --tail=80 2>&1 | tail -40", "desc": "Previous container logs (crash output)"},
        {"cmd": "oc describe pod {pod} -n {ns} 2>&1 | grep -A10 'Last State:'", "desc": "Last container state (exit code, OOM, error)"},
        {"cmd": "oc describe pod {pod} -n {ns} 2>&1 | grep -A5 'Resources:'", "desc": "Resource requests and limits"},
        {"cmd": "oc get events -n {ns} --field-selector involvedObject.name={pod} --sort-by='.lastTimestamp' 2>&1 | tail -10", "desc": "Pod events timeline"},
        {"cmd": "oc describe pod {pod} -n {ns} 2>&1 | grep -A3 'Restart Count:'", "desc": "Restart count and pattern"},
    ],
    "pod-evicted-disk": [
        {"cmd": "oc get pod {pod} -n {ns} -o wide 2>&1 | tail -1", "desc": "Pod details (shows which node)"},
        {"cmd": "oc describe pod {pod} -n {ns} 2>&1 | grep -A5 'Status:\\|Message:\\|Reason:'", "desc": "Pod eviction reason details"},
        {"cmd": "oc get events -n {ns} --field-selector involvedObject.name={pod} --sort-by='.lastTimestamp' 2>&1 | tail -10", "desc": "Pod events"},
        {"cmd": "oc get nodes --no-headers 2>&1 | grep -E 'NotReady|SchedulingDisabled'", "desc": "Nodes with issues"},
        {"cmd": "oc describe node $(oc get pod {pod} -n {ns} -o jsonpath='{{.spec.nodeName}}' 2>/dev/null) 2>&1 | grep -A5 'DiskPressure' | head -8", "desc": "Node DiskPressure condition"},
        {"cmd": "oc get pods --field-selector spec.nodeName=$(oc get pod {pod} -n {ns} -o jsonpath='{{.spec.nodeName}}' 2>/dev/null) -A --no-headers 2>&1 | grep -ci evict", "desc": "Count of evicted pods on same node"},
    ],
    "pod-evicted-generic": [
        {"cmd": "oc describe pod {pod} -n {ns} 2>&1 | grep -A5 'Status:\\|Message:\\|Reason:'", "desc": "Pod eviction details"},
        {"cmd": "oc get events -n {ns} --field-selector involvedObject.name={pod} --sort-by='.lastTimestamp' 2>&1 | tail -10", "desc": "Pod events"},
        {"cmd": "oc describe node $(oc get pod {pod} -n {ns} -o jsonpath='{{.spec.nodeName}}' 2>/dev/null) 2>&1 | grep -A20 'Conditions:'", "desc": "Node conditions of hosting node"},
    ],
    "mco-degraded": [
        {"cmd": "oc get mcp 2>&1", "desc": "MachineConfigPool status"},
        {"cmd": "oc get co machine-config -o yaml 2>&1 | grep -A10 'message:' | head -20", "desc": "MCO error message details"},
        {"cmd": "oc get nodes --no-headers 2>&1 | grep -E 'NotReady|SchedulingDisabled' | head -10", "desc": "Nodes that are NotReady or cordoned"},
        {"cmd": "oc get pods -n openshift-machine-config-operator --no-headers 2>&1 | grep -v Running | head -10", "desc": "Non-running MCD pods"},
        {"cmd": "oc get mcp worker -o yaml 2>&1 | grep -A10 'degradedMachineCount\\|message' | head -20", "desc": "Worker MCP degraded details"},
        {"cmd": "oc get events -n openshift-machine-config-operator --sort-by='.lastTimestamp' 2>&1 | tail -15", "desc": "Recent MCO events"},
        {"cmd": "oc get nodes --no-headers 2>&1 | grep SchedulingDisabled | head -5", "desc": "Nodes stuck in drain (SchedulingDisabled)"},
    ],
    "csi-crashloop": [
        {"cmd": "oc get pods -A --no-headers 2>&1 | grep -i csi | grep -v Running | head -10", "desc": "Non-running CSI pods"},
        {"cmd": "oc logs $(oc get pods -A --no-headers 2>&1 | grep -i csi | grep -i crash | head -1 | awk '{print \"-n \" $1 \" \" $2}') --previous --tail=50 2>&1 | tail -30", "desc": "Previous logs of crashing CSI pod"},
        {"cmd": "oc describe pod $(oc get pods -A --no-headers 2>&1 | grep -i csi | grep -v Running | head -1 | awk '{print $2 \" -n \" $1}') 2>&1 | grep -A10 'Last State:\\|Events:' | head -25", "desc": "Pod last state and events"},
        {"cmd": "oc get events -A --sort-by='.lastTimestamp' 2>&1 | grep -i csi | tail -10", "desc": "CSI-related events"},
        {"cmd": "oc get storagecluster -n openshift-storage 2>&1", "desc": "Storage cluster status"},
    ],
    "csi-pod-issue": [
        {"cmd": "oc get pods -A --no-headers 2>&1 | grep -i csi | grep -v Running | head -10", "desc": "Non-running CSI pods"},
        {"cmd": "oc get events -A --sort-by='.lastTimestamp' 2>&1 | grep -i csi | tail -10", "desc": "CSI-related events"},
        {"cmd": "oc get csidrivers 2>&1", "desc": "Registered CSI drivers"},
    ],
    "virt-handler-memory-deep": [
        {"cmd": "oc adm top pods -n openshift-cnv -l kubevirt.io=virt-handler --no-headers 2>&1 | sort -k3 -rh | head -10", "desc": "Top memory virt-handler pods"},
        {"cmd": "oc get vmi -A --no-headers 2>&1 | wc -l", "desc": "Total VMI count"},
        {"cmd": "oc get vmi -A -o wide --no-headers 2>&1 | awk '{print $4}' | sort | uniq -c | sort -rn | head -10", "desc": "VM count per node (top 10)"},
        {"cmd": "oc get ds virt-handler -n openshift-cnv -o yaml 2>&1 | grep -A10 'resources:' | head -12", "desc": "virt-handler resource requests/limits"},
        {"cmd": "oc get events -n openshift-cnv --field-selector reason=OOMKilled --sort-by='.lastTimestamp' 2>&1 | tail -5", "desc": "Recent OOM kills in CNV namespace"},
        {"cmd": "oc logs -n openshift-cnv $(oc get pods -n openshift-cnv -l kubevirt.io=virt-handler --no-headers -o name | head -1) --tail=30 2>&1 | grep -iE 'memory|oom|error|warn' | head -15", "desc": "virt-handler warning/error logs"},
    ],
}

DRILLDOWN_ANALYSIS_RULES = {
    "node-disk-pressure": [
        {"keywords": ["kubelet stopped posting", "nodestatusunknown"], "conclusion": "Node is DEAD - kubelet stopped posting status; all conditions show Unknown. This is NOT a disk issue, the node itself is unreachable", "confidence": "high",
         "fix": "1) Check if node is powered on via BMC/IPMI. 2) Try SSH: ssh core@<node-ip>. 3) If reachable: systemctl status kubelet, journalctl -u kubelet. 4) If not reachable: check network/switch, reboot via BMC.",
         "doc": "https://access.redhat.com/solutions/5765631",
         "followup": "node-dead-verify"},
        {"keywords": ["prometheus", "/prometheus", "prometheus-k8s"], "conclusion": "Prometheus TSDB is consuming excessive disk space", "confidence": "high",
         "fix": "Configure retention: oc edit configmap cluster-monitoring-config -n openshift-monitoring. Add 'retentionSize: 40GB' under prometheusK8s. Also set 'volumeClaimTemplate' to use a PVC instead of emptyDir.",
         "doc": "https://access.redhat.com/solutions/4976801"},
        {"keywords": ["/var/lib/containers"], "conclusion": "Container images and layers consuming disk", "confidence": "high",
         "fix": "Run garbage collection: crictl rmi --prune, or increase imageGCHighThresholdPercent in kubelet config",
         "doc": "https://docs.openshift.com/container-platform/latest/nodes/nodes/nodes-nodes-garbage-collection.html"},
        {"keywords": ["/var/log", "journal"], "conclusion": "Log files consuming disk space", "confidence": "medium",
         "fix": "Configure journald MaxRetentionSec or SystemMaxUse, check for pods with excessive logging",
         "doc": "https://access.redhat.com/solutions/6963786"},
        {"keywords": ["kubelet/pods", "emptydir", "ephemeral"], "conclusion": "Pod ephemeral storage (emptyDir volumes) consuming disk", "confidence": "medium",
         "fix": "Identify pods with large emptyDir usage and add ephemeral-storage limits"},
        {"keywords": ["95%", "96%", "97%", "98%", "99%", "100%"], "conclusion": "Filesystem is critically full (95%+)", "confidence": "high",
         "fix": "Identify the full filesystem from df -h output, then check its largest consumers with du -sh"},
        {"keywords": ["kubelet/pods", "kubelet\\pods"], "conclusion": "Pod ephemeral storage is a top disk consumer under /var/lib/kubelet/pods", "confidence": "high",
         "fix": "Identify the largest pod directories and their workloads. Check volume names inside each UUID directory to identify the pod (e.g. 'prometheus-k8s-db' = Prometheus). Cross-reference with: oc get pods --field-selector spec.nodeName=<node> -A"},
    ],
    "node-not-ready": [
        {"keywords": ["kubelet stopped posting", "nodestatusunknown"], "conclusion": "Kubelet stopped posting node status - node is unreachable or kubelet crashed", "confidence": "high",
         "fix": "1) Check if node is powered on via BMC/IPMI. 2) Try SSH: ssh core@<node-ip>. 3) If reachable: systemctl status kubelet, journalctl -u kubelet. 4) If not reachable: check network/switch.",
         "doc": "https://access.redhat.com/solutions/5765631",
         "followup": "node-dead-verify"},
        {"keywords": ["diskpressure", "disk pressure"], "conclusion": "Node Not Ready due to DiskPressure condition", "confidence": "high",
         "fix": "See disk pressure drilldown - identify and clean the top disk consumer",
         "follow_drilldown": "node-disk-pressure"},
        {"keywords": ["memorypressure", "memory pressure"], "conclusion": "Node Not Ready due to MemoryPressure condition", "confidence": "high",
         "fix": "See memory pressure drilldown - identify and stop the top memory consumer",
         "follow_drilldown": "node-memory-pressure"},
        {"keywords": ["oom", "out of memory", "killed process"], "conclusion": "Node Not Ready due to kernel OOM killer", "confidence": "high",
         "fix": "Check dmesg for which process was OOM-killed, increase node memory or reduce workload",
         "followup": "node-dead-verify"},
        {"keywords": ["kubelet", "stopped", "not running", "failed"], "conclusion": "Kubelet process is not running on the node", "confidence": "high",
         "fix": "SSH to node and check kubelet: journalctl -u kubelet --no-pager | tail -50",
         "followup": "node-dead-verify"},
        {"keywords": ["connection refused", "unreachable", "timeout"], "conclusion": "Node is network-unreachable or powered off", "confidence": "high",
         "fix": "Check physical/BMC connectivity, ping the node, check switch ports",
         "followup": "node-dead-verify"},
        {"keywords": ["i/o error", "disk error", "hardware"], "conclusion": "Hardware failure (disk I/O or other)", "confidence": "high",
         "fix": "Check BMC/IPMI logs, replace faulty hardware, cordon and drain the node",
         "followup": "node-dead-verify"},
    ],
    "node-memory-pressure": [
        {"keywords": ["oom", "killed"], "conclusion": "Kernel OOM killer is actively killing processes", "confidence": "high",
         "fix": "Identify which process was OOM-killed from dmesg, increase memory limits or reduce pods"},
        {"keywords": ["virt-handler", "virt-launcher"], "conclusion": "KubeVirt components consuming excessive memory (known issue with VM density)", "confidence": "high",
         "fix": "Reduce VM count per node, or increase virt-handler memory limits (CNV-71448)"},
        {"keywords": ["prometheus", "monitoring"], "conclusion": "Monitoring stack consuming excessive memory", "confidence": "medium",
         "fix": "Tune Prometheus memory by reducing retention, scrape interval, or number of targets"},
    ],
    "operator-crashloop": [
        {"keywords": ["oomkilled", "out of memory", "oom"], "conclusion": "Operator pod OOM-killed - needs higher memory limit", "confidence": "high",
         "fix": "Increase memory limit in operator deployment or subscription"},
        {"keywords": ["permission denied", "forbidden", "rbac"], "conclusion": "RBAC/permission error preventing operator from functioning", "confidence": "high",
         "fix": "Check ClusterRoleBindings and ServiceAccount permissions"},
        {"keywords": ["connection refused", "dial tcp", "no such host"], "conclusion": "Operator cannot reach a required service endpoint", "confidence": "high",
         "fix": "Check network policies and service availability in the namespace"},
        {"keywords": ["exit code 1", "exit code 2", "panic", "fatal"], "conclusion": "Application error in operator code (bug or bad config)", "confidence": "medium",
         "fix": "Check operator version, search Jira for matching bugs, consider reinstalling"},
    ],
    "pod-app-crash": [
        {"keywords": ["oomkilled", "exit code 137"], "conclusion": "Container OOM-killed (exit code 137 = SIGKILL from OOM)", "confidence": "high",
         "fix": "Increase memory limit in pod spec"},
        {"keywords": ["exit code 1", "error", "exception"], "conclusion": "Application runtime error", "confidence": "medium",
         "fix": "Check application logs for the specific error"},
        {"keywords": ["exit code 2", "usage", "invalid"], "conclusion": "Invalid arguments or configuration", "confidence": "medium",
         "fix": "Check ConfigMaps and environment variables passed to the pod"},
    ],
    "pod-evicted-disk": [
        {"keywords": ["kubelet stopped posting", "nodestatusunknown"], "conclusion": "Node is dead/unreachable - kubelet stopped. Pods were evicted as a consequence", "confidence": "high",
         "fix": "Check node power/network. SSH to node and check kubelet: systemctl status kubelet",
         "doc": "https://access.redhat.com/solutions/5765631",
         "followup": "node-dead-verify"},
        {"keywords": ["diskpressure", "disk pressure"], "conclusion": "Node has DiskPressure - kubelet is evicting pods to free ephemeral storage", "confidence": "high",
         "fix": "Identify top disk consumers on the node. Common culprits: Prometheus TSDB, container images, pod logs. Run: du -sh /var/lib/containers /var/lib/kubelet /var/log on the node.",
         "doc": "https://access.redhat.com/solutions/4976801",
         "follow_drilldown": "node-disk-pressure"},
    ],
    "pod-evicted-generic": [
        {"keywords": ["diskpressure"], "conclusion": "Pod evicted due to DiskPressure on the node", "confidence": "high",
         "fix": "Free disk space on the node or increase storage capacity",
         "follow_drilldown": "node-disk-pressure"},
        {"keywords": ["memorypressure"], "conclusion": "Pod evicted due to MemoryPressure on the node", "confidence": "high",
         "fix": "Reduce memory usage or add more memory to the node",
         "follow_drilldown": "node-memory-pressure"},
        {"keywords": ["evict"], "conclusion": "Pod evicted by kubelet due to resource pressure", "confidence": "medium",
         "fix": "Check node conditions to identify which resource is under pressure"},
    ],
    "mco-degraded": [
        {"keywords": ["context deadline exceeded", "timeout"], "conclusion": "MachineConfig apply timed out - node drain or reboot took too long. Likely a pod with a PodDisruptionBudget blocking the drain", "confidence": "high",
         "fix": "1) Check stuck nodes: oc get nodes | grep SchedulingDisabled. 2) Check PDBs: oc get pdb -A. 3) Check what's blocking drain: oc get pods --field-selector spec.nodeName=<node> -A | grep -v Completed",
         "doc": "https://access.redhat.com/solutions/5414371",
         "followup": "mco-drain-blocked"},
        {"keywords": ["notready", "unavailable"], "conclusion": "MCP degraded because a node went NotReady during update", "confidence": "high",
         "fix": "Check the NotReady node, fix it first, then MCO will recover automatically",
         "followup": "mco-drain-blocked"},
        {"keywords": ["schedulingdisabled"], "conclusion": "A node is stuck in SchedulingDisabled (drain did not complete)", "confidence": "high",
         "fix": "Check what's blocking drain on the stuck node, then uncordon: oc adm uncordon <node>",
         "followup": "mco-drain-blocked"},
        {"keywords": ["failed to resync", "resync"], "conclusion": "MCO failed to resync to target version - possible incompatible custom MachineConfig", "confidence": "high",
         "fix": "Check for custom MachineConfigs: oc get mc | grep -v rendered | grep -v 00-. Remove or fix incompatible custom configs."},
        {"keywords": ["degraded", "machine-config-daemon"], "conclusion": "MachineConfigDaemon on one or more nodes is reporting degraded", "confidence": "medium",
         "fix": "Check MCD logs on degraded nodes: oc logs -n openshift-machine-config-operator <mcd-pod> --tail=50",
         "followup": "mco-drain-blocked"},
    ],
    "csi-crashloop": [
        {"keywords": ["oomkilled", "oom", "exit code 137"], "conclusion": "CSI controller pod OOM-killed - needs higher memory limit", "confidence": "high",
         "fix": "Increase memory limit in the CSI controller deployment"},
        {"keywords": ["permission denied", "forbidden", "rbac"], "conclusion": "CSI controller lacks required RBAC permissions", "confidence": "high",
         "fix": "Check ClusterRoleBindings for the CSI service account"},
        {"keywords": ["connection refused", "dial tcp", "no such host"], "conclusion": "CSI controller cannot connect to the storage backend", "confidence": "high",
         "fix": "Check storage backend connectivity and network policies"},
        {"keywords": ["needsreinstall", "installcheckfailed", "installwaiting"], "conclusion": "OLM CSV reports CSI operator needs reinstall - deployment not available. The operator installation is broken.", "confidence": "high",
         "fix": "1) Check CSV status: oc get csv -n openshift-storage | grep csi. 2) Try deleting the CSV to trigger reinstall: oc delete csv <name> -n openshift-storage. 3) Check if the subscription is healthy: oc get sub -n openshift-storage.",
         "doc": "https://access.redhat.com/solutions/6005941"},
        {"keywords": ["leader election", "failed to acquire"], "conclusion": "CSI controller leader election failure - possible stale lock", "confidence": "medium",
         "fix": "Delete the leader election ConfigMap/Lease and restart the CSI pods"},
        {"keywords": ["crashloopbackoff", "error", "fail"], "conclusion": "CSI controller is crash-looping - check logs for the specific error", "confidence": "medium",
         "fix": "Check previous container logs: oc logs <pod> -n <ns> --previous"},
    ],
    "csi-pod-issue": [
        {"keywords": ["evicted"], "conclusion": "CSI pod was evicted due to resource pressure on the node", "confidence": "medium",
         "fix": "Check node conditions and consider dedicated nodes for storage pods"},
        {"keywords": ["pending"], "conclusion": "CSI pod is stuck in Pending state", "confidence": "medium",
         "fix": "Check pod events for scheduling issues: oc describe pod <pod> -n <ns>"},
    ],
    "virt-handler-memory-deep": [
        {"keywords": ["oomkilled", "oom"], "conclusion": "virt-handler is being OOM-killed. Memory limit too low for current VM density", "confidence": "high",
         "fix": "Increase virt-handler memory limit via HCO: spec.infra.nodePlacement.tolerations or patch the DaemonSet directly. CNV-71448",
         "doc": "https://issues.redhat.com/browse/CNV-71448"},
        {"keywords": ["error", "fail", "timeout"], "conclusion": "virt-handler experiencing errors in addition to high memory usage", "confidence": "medium",
         "fix": "Check virt-handler logs for root cause errors. High memory may be a side effect.",
         "followup": "virt-handler-errors-deep"},
    ],
}

FOLLOWUP_COMMANDS = {
    "node-dead-verify": [
        {"cmd": "ping -c 3 -W 2 {node_ip} 2>&1 || echo PING_FAILED", "desc": "Network reachability (ICMP ping)"},
        {"cmd": "ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes core@{node_ip} 'uptime' 2>&1 || echo SSH_UNREACHABLE", "desc": "SSH reachability check"},
        {"cmd": "ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes core@{node_ip} 'systemctl is-active kubelet; systemctl status kubelet --no-pager -l 2>&1 | head -15' 2>&1 || echo SSH_CMD_FAILED", "desc": "Kubelet service status on the node"},
        {"cmd": "ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes core@{node_ip} 'journalctl -u kubelet --since \"30 min ago\" --no-pager 2>&1 | tail -25' 2>&1 || echo SSH_CMD_FAILED", "desc": "Recent kubelet journal logs"},
        {"cmd": "ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes core@{node_ip} 'df -h / /var /var/lib/containers 2>&1' 2>&1 || echo SSH_CMD_FAILED", "desc": "Disk usage on the node"},
        {"cmd": "ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o BatchMode=yes core@{node_ip} 'dmesg -T 2>/dev/null | tail -25 || dmesg | tail -25' 2>&1 || echo SSH_CMD_FAILED", "desc": "Recent kernel messages (hardware errors, OOM, panic)"},
    ],
    "mco-drain-blocked": [
        {"cmd": "oc get pdb -A --no-headers 2>&1", "desc": "PodDisruptionBudgets blocking drain"},
        {"cmd": "oc get nodes --no-headers 2>&1 | grep SchedulingDisabled | awk '{print $1}'", "desc": "Nodes stuck in SchedulingDisabled"},
        {"cmd": "stuck=$(oc get nodes --no-headers 2>&1 | grep SchedulingDisabled | head -1 | awk '{print $1}'); [ -n \"$stuck\" ] && oc get pods --field-selector spec.nodeName=$stuck -A --no-headers 2>&1 | grep -vE 'Completed|Running' | head -15 || echo '(no stuck nodes found)'", "desc": "Non-running pods on stuck node (blocking drain)"},
        {"cmd": "oc get pods -A --no-headers 2>&1 | grep Terminating | head -10", "desc": "Pods stuck in Terminating state"},
        {"cmd": "stuck=$(oc get nodes --no-headers 2>&1 | grep SchedulingDisabled | head -1 | awk '{print $1}'); [ -n \"$stuck\" ] && oc get pods --field-selector spec.nodeName=$stuck -A --no-headers 2>&1 | wc -l || echo '0'", "desc": "Total pods remaining on stuck node"},
        {"cmd": "oc logs -n openshift-machine-config-operator $(oc get pods -n openshift-machine-config-operator --no-headers 2>/dev/null | grep machine-config-daemon | head -1 | awk '{print $1}') --tail=30 2>&1 | grep -iE 'error|fail|drain|timeout|evict' | head -10", "desc": "MCD error logs related to drain"},
    ],
    "virt-handler-errors-deep": [
        {"cmd": "oc logs -n openshift-cnv $(oc get pods -n openshift-cnv -l kubevirt.io=virt-handler --no-headers -o name 2>/dev/null | head -1) --tail=100 2>&1 | grep -iE 'error|warn|fail|timeout|refused|tls|cert|oom' | head -25", "desc": "virt-handler error/warning log lines"},
        {"cmd": "oc get pods -n openshift-cnv 2>&1 | grep -E 'virt-api|virt-controller' | head -5", "desc": "virt-api and virt-controller status"},
        {"cmd": "oc get vmi -A --no-headers 2>&1 | awk '{print $4}' | sort | uniq -c | sort -rn | head -5", "desc": "VM count per node (top 5)"},
        {"cmd": "oc get events -n openshift-cnv --sort-by='.lastTimestamp' 2>&1 | grep -iE 'error|fail|oom|kill' | tail -10", "desc": "Recent error events in CNV namespace"},
        {"cmd": "oc get ds virt-handler -n openshift-cnv -o yaml 2>&1 | grep -A8 'resources:' | head -10", "desc": "virt-handler resource limits"},
    ],
}

FOLLOWUP_ANALYSIS_RULES = {
    "node-dead-verify": [
        {"keywords": ["100% packet loss", "ping_failed", "ssh_unreachable"],
         "conclusion": "Node is completely unreachable - ping and SSH both fail. Machine is powered off, has a network failure, or experienced a kernel panic.",
         "confidence": "high",
         "fix": "Access via BMC/IPMI: 1) ipmitool -I lanplus -H <bmc-ip> power status, 2) If powered on: check console for kernel panic (ipmitool sol activate), 3) If powered off: power on via BMC, 4) Check switch port for the node NIC"},
        {"keywords": ["0 received", "ssh_unreachable"],
         "conclusion": "Node does not respond to ping or SSH. Machine may be powered off or has a complete network failure.",
         "confidence": "high",
         "fix": "Access via BMC/IPMI console. Check if machine is powered on and if NIC link is up."},
        {"keywords": ["ssh_unreachable", "bytes from"],
         "conclusion": "Node responds to ping but SSH is down. OS kernel is running but sshd or userspace may have crashed (possible kernel panic with network stack still alive).",
         "confidence": "high",
         "fix": "Access via BMC/IPMI console (ipmitool sol activate). Check: systemctl status sshd, systemctl status kubelet, free -h, df -h"},
        {"keywords": ["inactive", "dead"],
         "conclusion": "Node is reachable but kubelet service is stopped/dead.",
         "confidence": "high",
         "fix": "Root cause is in kubelet journal logs above. Common causes: certificate expiry, disk full (/var at 100%), OOM-killed. Do NOT blindly restart kubelet until cause is identified."},
        {"keywords": ["100%", "/var"],
         "conclusion": "Node is reachable but /var filesystem is full. This caused kubelet to stop functioning.",
         "confidence": "high",
         "fix": "Free disk on /var: du -sh /var/lib/containers /var/lib/kubelet /var/log on the node. Likely culprits: container images, pod logs, kubelet pods directory."},
        {"keywords": ["oom-killer", "out of memory", "killed process"],
         "conclusion": "Kernel OOM killer fired on the node. Kubelet or another critical process was killed.",
         "confidence": "high",
         "fix": "Check dmesg output above for which process was killed. Reduce memory consumption or increase node RAM."},
        {"keywords": ["panic", "bug:", "rip:", "call trace"],
         "conclusion": "Node experienced a kernel panic or kernel bug.",
         "confidence": "high",
         "fix": "Check BMC event log for timing. If recurring: check for known kernel bugs, update RHCOS, or replace hardware. Single event: node may recover after reboot via BMC."},
        {"keywords": ["hardware error", "mce:", "i/o error"],
         "conclusion": "Node has hardware errors (MCE or I/O). Likely failing disk, memory DIMM, or CPU.",
         "confidence": "high",
         "fix": "Check BMC SEL log for hardware events. Replace faulty component. Cordon node first if it recovers."},
        {"keywords": ["active", "running"],
         "conclusion": "Node is reachable and kubelet reports active/running. The NotReady condition may be transient or caused by API server connectivity issues.",
         "confidence": "medium",
         "fix": "Check kubelet journal for errors related to API server communication. Also check if node certificates have expired: oc get csr | grep Pending"},
    ],
    "mco-drain-blocked": [
        {"keywords": ["poddisruptionbudget", "pdb", "disruptionsallowed"],
         "conclusion": "PodDisruptionBudget is preventing node drain. MCO cannot evict pods protected by PDB, so the MachineConfig update is stuck.",
         "confidence": "high",
         "fix": "Identify the blocking PDB from output above. Options: 1) Scale up the deployment so PDB allows disruption, 2) Temporarily relax the PDB minAvailable, 3) If safe, delete the PDB temporarily."},
        {"keywords": ["terminating"],
         "conclusion": "Pods stuck in Terminating state are blocking the node drain.",
         "confidence": "high",
         "fix": "Force-delete stuck pods: oc delete pod <pod> -n <ns> --grace-period=0 --force. Then drain will complete and MCO proceeds."},
        {"keywords": ["(no stuck nodes found)", "0"],
         "conclusion": "No nodes currently stuck in SchedulingDisabled. The MCO drain may have already completed or the timeout was transient.",
         "confidence": "medium",
         "fix": "Check if MCP is now progressing: oc get mcp. If still degraded, check MCO operator logs for the specific error."},
        {"keywords": ["pending", "containercreating"],
         "conclusion": "Pods on the stuck node cannot be rescheduled - other nodes may lack capacity or have taints/affinity constraints.",
         "confidence": "medium",
         "fix": "Check node capacity: oc adm top nodes. Ensure other nodes have room for the pods being drained."},
    ],
    "virt-handler-errors-deep": [
        {"keywords": ["connection refused", "dial tcp", "connect:"],
         "conclusion": "virt-handler cannot connect to virt-api or other KubeVirt services. Network or service issue.",
         "confidence": "high",
         "fix": "Check virt-api pods above. If not Running, restart: oc delete pod -n openshift-cnv -l kubevirt.io=virt-api. If Running, check network policies."},
        {"keywords": ["tls", "certificate", "x509"],
         "conclusion": "TLS/certificate error in virt-handler. Certificates may have expired or been rotated without virt-handler restart.",
         "confidence": "high",
         "fix": "Restart virt-handler pods: oc delete pods -n openshift-cnv -l kubevirt.io=virt-handler. If persists, check HCO operator and cert-manager."},
        {"keywords": ["oomkilled", "oom", "killed"],
         "conclusion": "virt-handler pods are being OOM-killed. Current memory limit is too low for the VM density on these nodes.",
         "confidence": "high",
         "fix": "Increase memory limit from resource limits shown above. With high VM density, 2-4Gi is recommended. See CNV-71448.",
         "doc": "https://issues.redhat.com/browse/CNV-71448"},
        {"keywords": ["timeout", "context deadline"],
         "conclusion": "virt-handler experiencing timeouts communicating with KubeVirt control plane. Possible overload or network latency.",
         "confidence": "medium",
         "fix": "Check cluster network health and virt-api/virt-controller pod status. May resolve after reducing VM density."},
    ],
}
