apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: source-dv
  namespace: source-ns
spec:
  source:
    registry:
      url: "docker://quay.io/containerdisks/fedora:latest"
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization
    volumeMode: Block
